///////////////////////////////////////////////////////////
//  Account.cs
//  Implementation of the Class Account
//  Generated by Enterprise Architect
//  Created on:      07-Dec-2024 8:55:05 PM
//  Original author: mayar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Account {

	private static int accountID;
	//private Date dateCreated;
	private string password;
	private string status;
	private string username;

	public Account(){

	}

	~Account(){

	}

}//end Account