///////////////////////////////////////////////////////////
//  Administrator.cs
//  Implementation of the Class Administrator
//  Generated by Enterprise Architect
//  Created on:      07-Dec-2024 8:52:09 PM
//  Original author: mayar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Administrator : User {

	//public Message m_Message;

	public Administrator(){

	}

	~Administrator(){

	}

	public void addAccount(){

	}

	public void addDestinationCategory(){

	}

	public void addFlightDetails(){

	}

	public void addService(){

	}

	public void assignRoles(){

	}

	public void deleteAccount(){

	}

	public void deleteDestinationCategory(){

	}

	public void deleteFlightDetails(){

	}

	public void deleteService(){

	}

	public void editAccount(){

	}

	public void editDestinationCategory(){

	}

	public void editFlightDetails(){

	}

	public void editService(){

	}

	public void performDatabaseBackup(){

	}

	public void sendMessages(){

	}

	public void setupAdminAccount(){

	}

}//end Administrator