///////////////////////////////////////////////////////////
//  Airport.cs
//  Implementation of the Class Airport
//  Generated by Enterprise Architect
//  Created on:      07-Dec-2024 8:52:12 PM
//  Original author: mayar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Airport {

	private static int airportID;
	private string airportName;
	private string code;
	public Plane m_Plane;

	public Airport(){

	}

	~Airport(){

	}

}//end Airport