///////////////////////////////////////////////////////////
//  Booking.cs
//  Implementation of the Class Booking
//  Generated by Enterprise Architect
//  Created on:      07-Dec-2024 8:52:13 PM
//  Original author: mayar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Booking {

	private static int bookingID;
	private string cabinClass;
	private Employer employer;
	private Flight flight;
	private string From;
	private double totalPrice;
	private Traveller traveller;
	public Payment m_Payment;

	public Booking(){

	}

	~Booking(){

	}

}//end Booking