///////////////////////////////////////////////////////////
//  Card.cs
//  Implementation of the Class Card
//  Generated by Enterprise Architect
//  Created on:      07-Dec-2024 8:52:14 PM
//  Original author: Manar Alsetrawi
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Card {

	private string cardHolderName;
	private int cardNumber;
	private string cardType;
	//private Date expireDate;
	private int PIN;
	private int securityCode;
	public Payment m_Payment;

	public Card(){

	}

	~Card(){

	}

}//end Card