///////////////////////////////////////////////////////////
//  Destination.cs
//  Implementation of the Class Destination
//  Generated by Enterprise Architect
//  Created on:      07-Dec-2024 8:55:22 PM
//  Original author: mayar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Destination {

	private string airportName;
	private string city;
	private string country;
	private Airport destinationAirport;
	private static int destinationID;
	private string region;
	public Airport m_Airport;

	public Destination(){

	}

	~Destination(){

	}

}//end Destination