///////////////////////////////////////////////////////////
//  Employer.cs
//  Implementation of the Class Employer
//  Generated by Enterprise Architect
//  Created on:      07-Dec-2024 8:52:22 PM
//  Original author: mayar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Employer : User, ICommonUserOperations {

	private Booking[] bookingsList;
	public Booking m_Booking;

	public Employer(){

	}

	~Employer(){

	}

	public void bookFlight(){

	}

	public void managePersonalAccount(){

	}

	public void processPayment(){

	}

	public void searchFlight(){

	}

	public void viewFlightDetails(){

	}

}//end Employer