///////////////////////////////////////////////////////////
//  ICommonUser.cs
//  Implementation of the Interface ICommonUser
//  Generated by Enterprise Architect
//  Created on:      07-Dec-2024 8:52:25 PM
//  Original author: 97333
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public interface ICommonUser  {

	

	/// 
	/// <param name="MessageID"></param>
	
}//end ICommonUser