///////////////////////////////////////////////////////////
//  ICommonUserOperations.cs
//  Implementation of the Interface ICommonUserOperations
//  Generated by Enterprise Architect
//  Created on:      07-Dec-2024 8:52:26 PM
//  Original author: Manar Alsetrawi
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public interface ICommonUserOperations  {

	void bookFlight();

	void managePersonalAccount();

	void searchFlight();

	void viewFlightDetails();
}//end ICommonUserOperations