///////////////////////////////////////////////////////////
//  Payment.cs
//  Implementation of the Class Payment
//  Generated by Enterprise Architect
//  Created on:      07-Dec-2024 8:52:29 PM
//  Original author: mayar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Payment {

	//private Date paymentDate;
	private static int paymentID;
	private string paymentStatus;
	///private Time paymentTime;
	public Reciept m_Reciept;

	public Payment(){

	}

	~Payment(){

	}

	public void generateReciept(){

	}

}//end Payment