///////////////////////////////////////////////////////////
//  Plane.cs
//  Implementation of the Class Plane
//  Generated by Enterprise Architect
//  Created on:      07-Dec-2024 8:52:30 PM
//  Original author: mayar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Plane {

	private int capacity;
	private Flight[] flightsList;
	private int model;
	private static int planeID;
	public Flight m_Flight;

	public Plane(){

	}

	~Plane(){

	}

}//end Plane