///////////////////////////////////////////////////////////
//  Reciept.cs
//  Implementation of the Class Reciept
//  Generated by Enterprise Architect
//  Created on:      07-Dec-2024 8:52:31 PM
//  Original author: Manar Alsetrawi
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Reciept {

	private int paymentID;
	private static int recieptID;
	private double totalAmount;

	public Reciept(){

	}

	~Reciept(){

	}

}//end Reciept