///////////////////////////////////////////////////////////
//  Service.cs
//  Implementation of the Class Service
//  Generated by Enterprise Architect
//  Created on:      07-Dec-2024 8:52:32 PM
//  Original author: 97333
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Service {

	private string description;
	private static int ServiceId;
	private string ServiceName;
	private double ServicePrice;
	public Booking m_Booking;

	public Service(){

	}

	~Service(){

	}

}//end Service