///////////////////////////////////////////////////////////
//  Ticket.cs
//  Implementation of the Class Ticket
//  Generated by Enterprise Architect
//  Created on:      07-Dec-2024 8:52:34 PM
//  Original author: Manar Alsetrawi
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ticket {

	private string gateNumber;
	private string seatNumber;
	private int ticketID;
	private string travellerName;

	public Ticket(){

	}

	~Ticket(){

	}

}//end Ticket