///////////////////////////////////////////////////////////
//  Traveller.cs
//  Implementation of the Class Traveller
//  Generated by Enterprise Architect
//  Created on:      07-Dec-2024 8:52:35 PM
//  Original author: mayar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Traveller : User, ICommonUserOperations {

	private Booking[] bookingsList;
	private string nationality;
	private string passportNumber;
	public Booking m_Booking;

	public Traveller(){

	}

	~Traveller(){

	}

	public void bookFlight(){

	}

	public void managePersonalAccount(){

	}

	public void payBooking(){

	}

	public void searchFlight(){

	}

	public void viewFlightDetails(){

	}

}//end Traveller