///////////////////////////////////////////////////////////
//  User.cs
//  Implementation of the Class User
//  Generated by Enterprise Architect
//  Created on:      07-Dec-2024 8:52:36 PM
//  Original author: mayar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public abstract class User : ICommonUser {

	protected String email;
	protected string firstName;
	protected string lastName;
	protected string phoneNumber;
	protected static int userID;
	public Account m_Account;

	public User(){

	}

	~User(){

	}

	public void login(){

	}

	public void logout(){

	}

	/// 
	/// <param name="messageID"></param>
	public void ReceiveMessage(int messageID){

	}

}//end User