///////////////////////////////////////////////////////////
//  UserFactory.cs
//  Implementation of the Class UserFactory
//  Generated by Enterprise Architect
//  Created on:      07-Dec-2024 8:52:38 PM
//  Original author: 97333
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class UserFactory {

	public UserFactory(){

	}

	~UserFactory(){

	}

	/// 
	/// <param name="userType"></param>
	public User CreateUser(int userType){

		return null;
	}

}//end UserFactory